- hosts: all
  var_files:
    - ../../vaults/ssh-pub.yml
    - ../../vaults/user.yml
  tasks:
    - name: Adding local ssh keys
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ ssh-key }}"

    - name: Harden sshd configuration
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - regexp: "^#?PermitRootLogin"
          line: "PermitRootLogin no"
        - regexp: "^^#?PasswordAuthentication"
          line: "PasswordAuthentication no"
        - regexp: "^#?AllowAgentForwarding"
          line: "AllowAgentForwarding no"
        - regexp: "^#?AllowTcpForwarding"
          line: "AllowTcpForwarding no"
        - regexp: "^#?MaxAuthTries"
          line: "MaxAuthTries 2"
        - regexp: "^#?MaxSessions"
          line: "MaxSessions 2"
        - regexp: "^#?TCPKeepAlive"
          line: "TCPKeepAlive no"
        - regexp: "^#?UseDNS"
          line: "UseDNS no"
        - regexp: "^#?AllowAgentForwarding"
          line: "AllowAgentForwarding no"